sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '10'
  - '9'
branches:
  only:
    - master
    - initial-setup
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate
